#pragma once
// LICENSE AND COPYRIGHT (C) INFORMATION
// https://github.com/vittorioromeo/Zancle/blob/master/license.md


////////////////////////////////////////////////////////////
// Headers
////////////////////////////////////////////////////////////
#include "Zancle/Config.hpp"

#include "Zancle/GLUtils/Export.hpp"

#include "Zancle/GLUtils/Glad.hpp" // not expensive, included everwhere `GLCheck.hpp` is included

#include "Zancle/Base/Assert.hpp"


namespace za::priv
{
////////////////////////////////////////////////////////////
/// \brief Decode and log a known OpenGL error
///
/// Translates a previously retrieved OpenGL error code into a human-readable
/// description and writes it to `priv::errMsg` along with the source
/// location of the offending call. When `ZA_FATAL_OPENGL_ERRORS` is
/// defined the function additionally triggers an assertion failure.
///
/// This function is invoked by `GlScopedChecker` and is not meant to be
/// called directly by user code; use the `glCheck` macro instead.
///
/// \param openGlError The OpenGL error code previously returned by `glGetError()`
/// \param file        Source file where the offending call is located
/// \param line        Line number in the source file where the call is located
/// \param expression  The evaluated expression as a string
///
////////////////////////////////////////////////////////////
[[gnu::cold]] ZA_GLUTILS_API void glCheckError(unsigned int openGlError, const char* file, unsigned int line, const char* expression);

////////////////////////////////////////////////////////////
/// \brief Log a notice that an unchecked OpenGL error existed prior to the current call
///
/// Used by `GlScopedChecker` upon construction to signal that an OpenGL
/// error was already pending before the wrapped call was executed. This
/// helps locate code that fails to drain errors via `glCheck`.
///
////////////////////////////////////////////////////////////
[[gnu::cold]] ZA_GLUTILS_API void printUncheckedPriorGlError();

////////////////////////////////////////////////////////////
/// \brief Helper class to check for OpenGL errors in debug mode
///
/// This RAII style class is used internally by the `glCheck` macro to
/// detect and report OpenGL errors during development. It captures the
/// location of an OpenGL call on construction (also detecting any
/// pre-existing unchecked error) and drains/checks the error queue
/// when the object is destroyed (i.e. after the wrapped OpenGL call
/// has executed).
///
////////////////////////////////////////////////////////////
struct GlScopedChecker
{
    ////////////////////////////////////////////////////////////
    [[gnu::always_inline]] explicit GlScopedChecker(const char* const  theFile,
                                                    const char* const  theExpression,
                                                    const unsigned int theLine) :
        file{theFile},
        expression{theExpression},
        line{theLine}
    {
        const unsigned int openGlError = glGetError();

        if (openGlError == GL_NO_ERROR) [[likely]]
            return;

        printUncheckedPriorGlError();
        glCheckError(openGlError, file, line, expression);

        ZA_ASSERT(false);
    }

    ////////////////////////////////////////////////////////////
    [[gnu::always_inline]] ~GlScopedChecker()
    {
        while (true)
        {
            const unsigned int openGlError = glGetError();

            if (openGlError == GL_NO_ERROR) [[likely]]
                return;

            glCheckError(openGlError, file, line, expression);
        }
    }

    ////////////////////////////////////////////////////////////
    const char*        file;
    const char*        expression;
    const unsigned int line;
};

////////////////////////////////////////////////////////////
/// \brief Helper class to drain OpenGL errors via a custom error-query function
///
/// Used in contexts where the regular `glGetError` symbol is not yet
/// available (e.g. while the GL context is still being initialized) and
/// the caller has obtained an error-query function pointer manually.
/// On construction the error queue is asserted to be empty; on destruction
/// any errors generated by the wrapped expression are drained and ignored.
///
/// \tparam TFunc Callable returning an OpenGL error code (typically a
///               function pointer of type `GLenum(*)()`)
///
////////////////////////////////////////////////////////////
template <typename TFunc>
struct GlScopedCheckerIgnoreWithFunc
{
    ////////////////////////////////////////////////////////////
    [[gnu::always_inline]] explicit GlScopedCheckerIgnoreWithFunc(TFunc theFunc) : func{theFunc}
    {
        ZA_ASSERT(func() == GL_NO_ERROR);
    }

    ////////////////////////////////////////////////////////////
    [[gnu::always_inline]] ~GlScopedCheckerIgnoreWithFunc()
    {
        while (func() != GL_NO_ERROR)
            /* drain/ignore any error */;
    }

    ////////////////////////////////////////////////////////////
    TFunc func;
};

////////////////////////////////////////////////////////////
/// Macro to check every OpenGL API call
///
/// In debug builds, wraps the given OpenGL expression with a
/// `GlScopedChecker` that captures the source location and detects
/// errors before and after the call. In release builds (and on
/// Emscripten, where `glGetError` is prohibitively slow) the macro
/// expands to the bare expression with no overhead.
///
/// The wrapper preserves the value category and return type of the
/// expression, so `glCheck(glCreateShader(...))` can be used directly
/// in an assignment.
///
////////////////////////////////////////////////////////////
#if defined(ZA_DEBUG) && !defined(ZA_SYSTEM_EMSCRIPTEN) // `glCheck` is prohibitively slow on Emscripten

    #define glCheck(...) \
        (::za::priv::GlScopedChecker{__FILE__, #__VA_ARGS__, static_cast<unsigned int>(__LINE__)}, __VA_ARGS__)

// The variant below is used for calls that may legitimately produce
// errors (e.g. probing for optional functionality). The wrapper drains
// the resulting errors via a user-provided query function so that they
// don't pollute subsequent `glCheck` calls.

    #define glCheckIgnoreWithFunc(errorFunc, ...) (::za::priv::GlScopedCheckerIgnoreWithFunc{errorFunc}, __VA_ARGS__)

#else

    #define glCheck(...)                          (__VA_ARGS__)
    #define glCheckIgnoreWithFunc(errorFunc, ...) (__VA_ARGS__)

#endif


} // namespace za::priv
